-- Look up what daily data is missing from the btcclosingprice table --
Select * from test t
left join btcclosingprice btc
	on t.MYSQL_DateFormat = btc.date
where t.MYSQL_DateFormat between '2017-1-1 00:00:00' and now()
and btc.USD is null;


-- Load DimDate.csv into DimDate table, ignoring the header row
LOAD DATA LOCAL INFILE '~/workspace/Blockfund_test/Application/db/DimDate.csv' INTO TABLE DimDate FIELDS OPTIONALLY ENCLOSED BY '"' TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES (PK,DATE_ID,@CALENDAR_DATE,CY,FY,CALENDAR_QUARTER,CALENDAR_QUARTER_ID,CALENDAR_QUARTER_NAME,FINANCIAL_QUARTER,FINANCIAL_QUARTER_ID,FINANCIAL_QUARTER_NAME,SEASON,CALENDAR_MONTH_ID,CM,MONTH_NAME,MONTH_ABBREVIATION,FINANCIAL_MONTH_ID,FM,CALENDAR_WEEK_ID,CALENDAR_WEEK,FINANCIAL_WEEK_ID,FINANCIAL_WEEK,DAY_OF_CALENDAR_YEAR,DAY_OF_FINANCIAL_YEAR,DAY_OF_MONTH,WEEK_DAY_NUMBER,WEEK_DAY_NAME,WEEK_DAY_ABBREVIATION,IS_A_WEEKEND_DAY,IS_A_PUBLIC_HOLIDAY,IS_A_LEAP_YEAR,IS_A_SPECIAL_DAY,DAYS_IN_CALENDAR_YEAR,DAYS_IN_FINANCIAL_YEAR,WEEKDAYS_IN_CALENDAR_YEAR,WEEKDAYS_IN_FINANCIAL_YEAR,WORKDAYS_IN_CALENDAR_YEAR,WORKDAYS_IN_FINANCIAL_YEAR,DAYS_IN_CALENDAR_YEAR_SOFAR,DAYS_IN_FINANCIAL_YEAR_SOFAR,WEEKDAYS_IN_CALENDAR_YEAR_SOFAR,WEEKDAYS_IN_FINANCIAL_YEAR_SOFAR,WORKDAYS_IN_CALENDAR_YEAR_SOFAR,WORKDAYS_IN_FINANCIAL_YEAR_SOFAR,DAYS_IN_MONTH,WEEKDAYS_IN_MONTH,WORKDAYS_IN_MONTH,DAYS_IN_MONTH_SOFAR,WEEKDAYS_IN_MONTH_SOFAR,WORKDAYS_IN_MONTH_SOFAR) SET CALENDAR_DATE = STR_TO_DATE(@CALENDAR_DATE, '%Y-%m-%d %H:%i:%s'); 


CREATE TABLE users(
 `id` INTEGER NOT NULL AUTO_INCREMENT ,
 `username` TEXT NOT NULL ,
 `hash` TEXT NOT NULL ,
 `cash` DECIMAL( 30, 6 ) NOT NULL DEFAULT 10000.00,
PRIMARY KEY (  `id` )
)